### ISSUE TITLE
run-pixelweb fails to launch

### ISSUE THREAD

**Issue by praeluceo** [ManiacalLabs/PixelWeb#2]
run-pixelweb has an error expressed here:

`sudo run-pixelweb
Traceback (most recent call last):
  File "/usr/local/bin/run-pixelweb", line 3, in <module>
    from pixelweb.pixelweb import startServer
  File "/usr/local/lib/python2.7/dist-packages/pixelweb/pixelweb.py", line 8, in <module>
    from actions import *
  File "/usr/local/lib/python2.7/dist-packages/pixelweb/actions.py", line 10, in <module>
    from bpmanager import *
  File "/usr/local/lib/python2.7/dist-packages/pixelweb/bpmanager.py", line 4, in <module>
    from static_objects import *
  File "/usr/local/lib/python2.7/dist-packages/pixelweb/static_objects.py", line 35, in <module>
    moduleList.remove(None)
ValueError: list.remove(x): x not in list`

A hacked work-around is just to delete line 35 from https://pypi.python.org/simple/bibliopixel/:
moduleList.remove(None)

Then launching run-pixelweb at least succeeds, although I don't really know if that line was essential for some other part of the initialization process. Sorry for spamming you with issues!

**Comment by adammhaile** [comment]
Fixed in 36bd3ec69e1e4cff89d4a6be7def8fc2c40f31e0
Looks like you are running on a Pi... I was expecting some drivers not to load, causing None in the moduleList. I now check for None before trying to remove. Should work fine now.

Also... way to be on the cutting edge :) Haven't technically announced this yet. Monday!

**Comment by praeluceo** [comment]
Yes, it's a pi, and it's actually a fluke, I was looking to see if the bibliopixel repo had been updated (I had just fetched the tgz and didn't do the pip install or git clone earlier) and saw this, so fun, it looks great! Still a bit rough (my queue hasn't been advancing) but my cube is now much more hallween-esque for trick-or-treating this afternoon than it was an hour ago, with very little work, so awesome!

**Comment by adammhaile** [comment]
Your animations in the queue have to implement animComplete or you have to
set max frames. Watch this: https://youtu.be/WGmNFANYjck
