### ISSUE TITLE
i cant run queues

### ISSUE THREAD

**Issue by fizzers123** [ManiacalLabs/PixelWeb#3]
I could succesfully install everything, but i can't run queues.
No animations are aperaing, when i click on Start.

**Comment by adammhaile** [comment]
Do they do anything when you run them as normal animations (outside of a queue)?
Do you get any error messages either in the UI or in the console?
What animations are you running and with what parameters?

What device are you outputting to?

run "sudo run-pixelweb --update-depends" to make sure you have the latest of everything

**Comment by fizzers123** [comment]
THANKS a lot :P
 "sudo run-pixelweb --update-depends" could solve the issue.
Btw: Pixel Web is the most AWSOME thing EVER :DDDD

**Comment by fizzers123** [comment]
Do you have a way to controll it via "Soud to Light" ? (for LPD8806)

**Comment by adammhaile** [comment]
Awesome. Glad it works now! :)
There's a couple audio animations in the animation repo, like this one:
https://github.com/ManiacalLabs/BiblioPixelAnimations/blob/master/BiblioPixelAnimations/matrix/FFT_Audio_Animation.py

**Comment by fizzers123** [comment]
is there also one for a led stip ?

**Comment by adammhaile** [comment]
Not currently, no. If you take the matrix version and rewrite it as a strip
animation, you could just treat it as a 1-column matrix so that it averages
everything together.

**Comment by fizzers123** [comment]
ahh, ok thx.
Im still wondering if there is a way to change a anymation while it is runing.
It would be awsome to controll the Color and Speed dinamicly, while it is runing (wiht Faders etc.)

**Comment by adammhaile** [comment]
Use an animation class (BaseStripAnim):
https://github.com/ManiacalLabs/BiblioPixel/wiki/Writing-an-Animation
You can code it to do what ever you want while it's running.

**Comment by fizzers123** [comment]
OK, thx for your help,
