### ISSUE TITLE
Uncaught TypeError on fresh install

### ISSUE THREAD

**Issue by baldo** [ManiacalLabs/PixelWeb#9]
Having freshly installed (and thus no config yet), loading PixelWeb in Chrome and Firefox results in the following error:

`Uncaught TypeError: Cannot read property 'config' of null (simple.js:22)` 

As a workaround I set `val` to `255` on that line which allowed me to configure PixelWeb. After that I undid the change an PixelWeb would keep working.

**Comment by adammhaile** [comment]
Sorry about that, fixed in v1.1.2, just pushed.
`pip install pixelweb --upgrade`

**Comment by baldo** [comment]
Thank you for the quick reaction. Now I get:

`Uncaught ReferenceError: init_simple is not defined (main.js:761)`
`_finalLoad @ main.js:761`
`nextLoad @ main.js:776`

**Comment by adammhaile** [comment]
Sorry about that... upgrade again. Should be fixed now.

**Comment by baldo** [comment]
Thank you, works like a charm now.
